name: CI/CD - Raspberry Deploy

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}

      - name: Configurar SSH y desplegar en Raspberry
        run: 

          ssh -p ${{ secrets.PI_SSH_PORT }} -i ${{ secrets.PI_SSH_PRIVATE_KEY }} ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }}

          echo "📥 Haciendo pull del simulador..."
          git -C /home/deshollinador/diabecare-infra/diabecare-parche-simulator pull origin dev

          echo "🚀 Desplegando con Docker Compose..."
          cd /home/deshollinador/diabecare-infra/
          docker compose down
          docker compose up -d --build

          echo "✅ Despliegue completado."
          EOF
        env:
          PI_HOST: ${{ secrets.PI_HOST }}
          PI_USER: ${{ secrets.PI_USER }}
          PI_SSH_PORT: ${{ secrets.PI_SSH_PORT }}
          PI_SSH_PRIVATE_KEY: ${{ secrets.PI_SSH_PRIVATE_KEY }}
